import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Main from '@/components/Main'
import About from '@/components/About'
import Skills from '@/components/Skills'
import Projects from '@/components/Projects'
import Contact from '@/components/Contact'
import { createClient } from "next-sanity";

export async function getServerSideProps(context) {
  const client = createClient({
    projectId:process.env.PROJECT_ID,
    dataset:process.env.DATASET,
    useCdn:true
  });
  const query = `*[_type == "resume"]`;
  const portfolio = await client.fetch(query);

  const resumeQuery=`*[_type == 'resume'][0]{
    'url': resume.asset->url,
    'name': Name
  }`;
  const resumeUrl = await client.fetch(resumeQuery);

  return {
    props: {
      portfolio,resumeUrl
    }
  };
}

export default function Home({portfolio,resumeUrl}) {
  return (
    <div>
      <Head>
        <title>Rajaram | Web Developer</title>
        <meta name='description' content='Generated by Rajaram'/>
        <link rel='icon' href='/favicon.ico'/>
      </Head>
      <Navbar resume={resumeUrl}/>

      <Main/>
      <About/>
      <Skills/>
      <Projects/>
      <Contact/>
       
    </div>
  )
}

